### ISSUE TITLE
parsing fails: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by JanOdijk** [UUDigitalHumanitieslab/sastadev#18]
Traceback (most recent call last):
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\__main__.py", line 1313, in <module>
    main()
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\__main__.py", line 883, in main
    treebank, errordict, allorandalts = correcttreebank(origtreebank, targets, options.methodname, options.corr)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\correcttreebank.py", line 239, in correcttreebank
    newstree, orandalts = correct_stree(stree, method, corr)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\correcttreebank.py", line 519, in correct_stree
    ctmds: List[Correction] = getcorrections(cleanutttokens, method, fatstree)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\corrector.py", line 459, in getcorrections
    alternativemds = getalternatives(reducedtokensmd, method, tree, '0')
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\corrector.py", line 529, in getalternatives
    fatntree = fatparse(utterance, uttmd.tokens)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\treebankfunctions.py", line 1905, in fatparse
    stree = settings.PARSE_FUNC(utterance)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\sentence_parser.py", line 43, in parse
    xml = alp.parse_sentence(sentence)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\sentence_parser.py", line 25, in parse_sentence
    with self.connection() as s:
  File "C:\Users\Odijk101\Anaconda3\envs\sastadev\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev\src\sastadev\sentence_parser.py", line 17, in connection
    s = socket.create_connection((sastadev.conf.settings.ALPINO_HOST, sastadev.conf.settings.ALPINO_PORT))
  File "C:\Users\Odijk101\Anaconda3\envs\sastadev\lib\socket.py", line 728, in create_connection
    raise err
  File "C:\Users\Odijk101\Anaconda3\envs\sastadev\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Process finished with exit code 1

**Comment by JanOdijk** [comment]
Ik gebruik normaal natuurlijk de functies in alpino_parsing.py om Alpino aan te roepen

**Comment by JeltevanBoheemen** [comment]
Ah, hij staat standaard op de functie die een lokale alpino server verwacht. Ik zal het fixen.

**Comment by JeltevanBoheemen** [comment]
Resolved in 43a7ceae1f2139b7620843fc294d8fe88c0093e0

**Comment by JanOdijk** [comment]
Hoe krijg ik dat nu lokaal? Door git pull?
Hij zegt bij mij:
(base) D:\Dropbox\jodijk\myprograms\python\sastacode\mysastadev>git checkout feature/packaging
Switched to branch 'feature/packaging'
Your branch is up to date with 'origin/feature/packaging'.

Maar dat ie denkt dat ik up to date ben komt waarschijnlijk omdat hij niet weet dat jij al dingen veranderd hebt?

**Comment by JeltevanBoheemen** [comment]
Inderdaad `git pull`. Als je wil zien wat je hoeveel commits je voor/achter loopt t.o.v een remote, doe je eerst `git fetch`

**Comment by JanOdijk** [comment]
Het draait nu, werkt voor 1 file die ik getest heb. 
Ik moest nog 1 aanpassing doen, nl in mksilver.py, line 80

    colsok = checkpermformat(silverheader, silverdata, permsilvercolcount)

vervangen door 

    colsok = checkpermformat(silverheader, silverdata, permsilvercolcount, strict=False)

(door andere aanpassingen die ik gedaan had werkt strict=True (de default) niet meer. Zal ik die aanpassing committen en pushen naar origin? of stel je iets anders voor


Nu wil ik  ik een ander script gebruiken dat sastadev loslaat op meerdere files, vergelijkingen maakt met eerdere runs etc.
Daarvoor moe ik de dataroot specificeren en die moet bij mij zijn

D:\Dropbox\jodijk\Utrecht\Projects\SASTADATA

Hoe doe ik dat?

1 mogelijkheid die ik zie is 

settings.DATAROOT = r'D:\Dropbox\jodijk\Utrecht\Projects\SASTADATA'   

toevoegen aan conf.py. (na line 26

Of stel je iets anders voor?

Of moet ik dat anders doen?

**Comment by JeltevanBoheemen** [comment]
Het beste kun je op de plaats waar je sasta aanroept, dus in het script dat je gebruikt:

```python
from sastadev.conf import settings
settings.DATAROOT = 'D:\Dropbox\jodijk\Utrecht\Projects\SASTADATA'
```
Alle aanroepen nadat je dit instelt gebruiken dan de nieuwe locatie.

Als je de code in `sastadev.conf` aanpast komt dat weer in git terecht, en dat willen we vermijden.

**Comment by JanOdijk** [comment]
Ok, maar ik heb die dataroot in meerdere scripts nodig, dus  ik zou het maar een keer willen specificeren. het script waarin het dan opgenomen wordt zit trouwens ook in git, zij het in een ander git repository dan sastadev. Ik weet even niet precies wat nu de beste strategie is

**Comment by JeltevanBoheemen** [comment]
Het is niet erg om settings voor sastadev op te nemen in de git van het script wat je draait. 
Wat onhandig is, is om de settings direct in de sastadev code op te nemen, want dan is het voor alle instanties van sastadev meteen de default.

Als je meerdere script hebt (in dezelfde directory) die dezelfde sastadev settings gebruiken, kun je bijvoorbeeld in een `__init__.py` bestand de setting instellen.
